arch: ppc64le
dist: xenial
sudo: required
compiler: clang
python: 3.7
node_js: 10
install:
  - sudo apt update -y
  - sudo apt install -y build-essential clang git vim cmake python bzip2 tar pkg-config libcups2-dev pkg-config libnss3-dev libssl-dev libglib2.0-dev libgnome-keyring-dev libpango1.0-dev libdbus-1-dev libatk1.0-dev libatk-bridge2.0-dev libgtk-3-dev libkrb5-dev libpulse-dev libxss-dev re2c subversion curl libasound2-dev libpci-dev mesa-common-dev gperf bison uuid-dev clang-format libatspi2.0-dev libnotify-dev libgconf2-dev libcap-dev libxtst-dev libxss1 python-dbusmock openjdk-8-jre clang-format wget libnotify-dev
  - sudo apt install -y software-properties-common
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update -y
  
before_script:
  - git clone https://github.com/ninja-build/ninja
  - cd ninja
  - git checkout v1.7.2
  - ./configure.py --bootstrap
  - export PATH=$(pwd):$PATH
  - cd ..
  - #gn build
  - git clone https://gn.googlesource.com/gn
  - cd gn
  - git checkout 81ee1967d3fcbc829bac1c005c3da59739c88df9
  - sed -i '/-static-libstdc++/d' build/gen.py
  - python build/gen.py
  - ninja -C out
  - cd ../
  - export DEPOT_TOOLS_GN="$(pwd)/gn/out/gn"
  - #
  - git clone https://github.com/leo-lb/depot_tools
  - git -C depot_tools checkout ppc64le
  - export DEPOT_TOOLS_UPDATE=0
  - export PATH=$(pwd)/gn/out:$PATH:$(pwd)/depot_tools
  - export VPYTHON_BYPASS="manually managed python not supported by chrome operations"
  - export GYP_DEFINES="disable_nacl=1"
  - mkdir -p electron-gn && cd electron-gn
  - gclient config --name "src/electron" --unmanaged https://github.com/leo-lb/electron@7-2-x
  - gclient sync --with_branch_heads --with_tags --no-history

script:
  - cd src
  - cd third_party/libvpx
  - mkdir -p source/config/linux/ppc64
  - ./generate_gni.sh
  - cd ../../
  - cd third_party/ffmpeg
  - ./chromium/scripts/build_ffmpeg.py linux ppc64
  - ./chromium/scripts/generate_gn.py
  - ./chromium/scripts/copy_config.sh
  - cd ../../
  - ls
